# Generated by Django 5.0.4 on 2024-04-27 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0002_admin"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Admin",
        ),
    ]
